# Generated by Django 3.1.4 on 2020-12-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=150, unique=True, verbose_name='Phone number'),
        ),
    ]
